server_url: http://[your-server-ip]:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
private_key_path: /etc/headscale/private.key
noise:
    private_key_path: /etc/headscale/noise_private.key

ip_prefixes:
    # - fd7a:115c:a1e0::/48
    - 100.64.0.0/10

# Disables the automatic check for headscale updates on startup
disable_check_updates: true

db_type: sqlite3
db_path: /etc/headscale/db.sqlite

log:
    format: text
    level: info

dns_config:
    override_local_dns: true
    nameservers:
        - 1.1.1.1
        - 1.0.0.1
        # - 2606:4700:4700::1111
        # - 2606:4700:4700::1001
    magic_dns: true
    base_domain: luislavena.info

logtail: 
    enabled: false
