version: "3"

services:
    reverse-proxy:
        # build: ./nginx
      image: nginx
      container_name: "reverse-proxy-nginx"
      restart: unless-stopped
      volumes:
        - ./nginx/www:/usr/share/nginx/html # web page directory
        - ./nginx/www:/etc/nginx/html # web page directory
        - ./nginx/etc/hosts:/etc/hosts # Host file
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx default configuration file
        - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf # Default nginx extra configuration file
        - ./nginx/backend-not-found.html:/usr/share/nginx/html/backend-not-found.html # Error 404 page
        - ./nginx/backend-not-found.html:/var/www/html/backend-not-found.html # Error 404 page
        - ./nginx/includes:/etc/nginx/includes # Additional config files to use with default.conf
        ## SSL/TLS Encryption files
        - ./nginx/ssl/[ssl-cert].crt:/etc/ssl/certs/nginx/[ssl-cert].crt # SSL Certification (Optional)
        - ./nginx/ssl/[private-key].key:/etc/ssl/certs/nginx/[private-key].key # Private Key generated with the SSL/TLS certificate (Optional)
      ports:
          # Port forwarding the host system's port to the container's port
          # [host system port]:[container port]
          - 80:80 # HTTP
          - 443:443 # HTTPS
          ## External link ports

