version: "3"

networks:
    default:

services:
    # Pi-hole DNS Server, Resolver, Sinkhole, Firewall, Router
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          - "80:80/tcp"
          - "443:443/tcp"
        environment:
          TZ: 'Asia/Singapore' # This is the timezone
        volumes:
          - './pihole/etc-pihole/:/etc/pihole/'
          - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
          - 127.0.0.1
          - 1.1.1.1
          - 192.168.1.123
        cap_add:
          - NET_ADMIN
        restart: always


