# docker compose environment file for building and starting up custom code-server image using ArchLinux as the base image
# Repositories
# - GitHub:
#   + https://github.com/coder/code-server
#   + https://github.com/linuxserver/code-server
# Setup
# - Pre-Requisites
#   + Create code-server (VSCode) configuration directories "${PWD}/code-server/go/config"
#   + Create workspace directories "${PWD}/code-server/go/workspace"
version: "3.7"
services:
  go-code-server:
    image: thanatisia/arch-code-server:latest
    container_name: arch-code-server
    build: 
      context: .
      dockerfile: "../Dockerfiles/arch.code-server.Dockerfile"
    restart: unless-stopped
    environment:
      ## Map Environment Variables into the container
      ### Server
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD} # Optional; Specify the password to access the VS Code instance
      - HASHED_PASSWORD=${HASHED_PASSWORD:-} # Optional; SHA256 hash hex digest of the password
      - SUDO_PASSWORD=${SUDO_PASSWORD} # Optional; Specify the sudo password for the container's root user
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH:-} # Optional; SHA256 hash hex digest of the sudo password string
      - PROXY_DOMAIN=${PROXY_DOMAIN:-code-server.my.domain} # Optional; Specify the Proxy Domain to connect the code server through
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE:-/config/workspace} # Optional; Specify the path in the container's filesystem tree where the default workspace is located
    ports:
      ## Port Forward/Translate/Map ports from the host system to the container
      ## [host-system-ip-address]:[host-system-port]:[container-port]
      - 8080:8080 # Port Number for WebUI and HTTP
      - 8443:8443 # Port Number for WebUI HTTPS
    volumes:
      ## Mount volumes from the host system to the container
      ## [host-system-volume]:[container-volume]:[permission]
      - "${PWD}/code-server/go/config:/config" # Mount the code-server configurations directory
      - "${PWD}/code-server/go/workspace:/config/workspace" # Mount your default workspace directory (set the environment variable 'DEFAULT_WORKSPACE'

