version: "3.3"
services:
    guacamole:
        image: maxwaldorf/guacamole
        container_name: guacamole
        ports:
            - "8080:8080"
        volumes:
            - '$PWD/root/etc/guac:/config'
        restart: always
