# Docker-compose for
# yt-dlp Video Downloader WebUI
# Service Author: alexta69
# Service Name: metube
# URL: https://github.com/alexta69/metube
# Configurations: 
#   - GHCR: https://github.com/alexta69/metube/pkgs/container/metube

version: '3.5'

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      # Port forward/translate from host system port to container port
      # [host-system-port]:[container-port]
      - 8082:8081
    volumes:
      # Mount volumes from host system volume to container volume
      # [host-system-volume]:[container-volume]:[permission]
      - "${PWD}/metube/downloads:/downloads" # metube downloads location

