version: "3.5"
services:
    mysql:
        # MySQL Database Docker compose
        image: mysql:latest
        container_name: mysql
        env_file:
            # Environment file
            # - please place all your MYSQL environment variables in here
            # namely:
            #   - MYSQL_ROOT_PASSWORD : Root password
            #   - MYSQL_USER : MySQL Username
            #   - MYSQL_PASSWORD : MySQL user password
            #   - MYSQL_DATABASE : MySQL Database Name
            - "${PWD}/mysql/.env"
        ports:
            # Port forwarding/translation between host system and container
            # - [host system port]:[container port]
            # Equivalent to docker run's : '-p'
            # MySQL default port: 3306
            - "3306:3306"
