version: "3.7"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    restart: unless-stopped
    environment:
      ## Set Environment Variables
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - MENU_VERSION=1.9.9 # Optional
      # - PORT_RANGE=30000:30010 # Optional
      # - SUBFOLDER=/ # Optional
    volumes:
      ## Mount volumes from host system into container
      ## [host-system-volume]:[container-volume]:[permission]
      - "${PWD}/netbootxyz/config:/config"
      - "${PWD}/netbootxyz/assets:/assets" # Optional
    ports:
      ## Port Forward/Translate/Map from Host system port to container port
      ## [ip-address]:[host-system-port]:[container-port]
      - "3000:3000"
      - "69:69/udp"
      - "8080:80" # Optional

