version: "3.5"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GIT=1000
      - HTTP_PORT=3000 # Define the port for the server to listen; Leave as default (3000)
      - LOCAL_ROOT_URL="http://192.168.1.5:3000" # Required to set a custom root URL from localhost
    restart: unless-stopped
    volumes:
      - "./gitea/data:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

