version: "3"

networks:
    default:

volumes:
  # Named mounted volume
  ikev2-vpn-data:

services:
    # Pi-hole DNS Server, Resolver, Sinkhole, Firewall, Router
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          - "80:80/tcp"
          - "443:443/tcp"
        environment:
          TZ: 'Asia/Singapore' # This is the timezone
        volumes:
          - './pihole/etc-pihole/:/etc/pihole/'
          - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
          - 127.0.0.1
          - 1.1.1.1
          - 192.168.1.123
        cap_add:
          - NET_ADMIN
        restart: always

    vpn:
        # Set image
        image: hwdsl2/ipsec-vpn-server
        restart: always
        env_file:
          - ./ipsec-vpn/vpn.env
        ports:
          - "500:500/udp"
          - "4500:4500/udp"
        privileged: true
        hostname: ipsec-vpn-server
        container_name: ipsec-vpn-server
        volumes:
          - ikev2-vpn-data:/etc/ipsec.d/
          - /lib.modules:/lib/modules:ro
