# docker-compose 
# for 
# jgraph/draw.io
version: "3.7"
services:
  draw-io:
    image: jgraph/drawio:latest
    container_name: draw-io
    restart: unless-stopped
    ## Environment Variables
    # env_file: "./drawio/secrets/.env" # Uncomment this to useEnvironment Variable secrets file
    # environment:
      # DRAWIO_BASE_URL: Your deployment base URL. For example, https://drawio.example.com or https://www.example.com/drawio if it is deployed into a folder.
      # DRAWIO_CSP_HEADER: (Optional) Your website Content-Security-Policy if you want to customize it.
      # DRAWIO_VIEWER_URL: (Optional) If you want to host a draw.io viewer also, set the viewer URL. For example, https://drawio.example.com/js/viewer.min.js
      # DRAWIO_LIGHTBOX_URL: (Optional) If you want to host a draw.io viewer also, set the lightbox URL. For example, https://drawio.example.com
      # DRAWIO_CONFIG: (Optional) draw.io configuration JSON. Documentation
      # DRAWIO_USE_HTTP: (Optional and INSECURE) If your setup uses http only and you understand the risks (for example, sending OAuth tokens over http), set DRAWIO_USE_HTTP=1. Caution: Use at your own risk.
    ## Networking
    ports:
      ## Port forwarding/mapping from host system port to container port
      ## [ip-address]:[host-system-port]:[container-port]
      - "8086:8080" # HTTP WebUI
      - "8443:8443" # HTTPS WebUI
    ## Volumes
    # volumes:
      ## Map host system volume into container volume
      ## [host-system-volume]:[container-volume]:[permission]
