version: "3.7"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: "flaresolverr"
    restart: unless-stopped
    environment:
      ## Environment Variables; Use 'env_file' for secrets
      LOG_LEVEL: info
    ports:
      ## Port Forward/Translate/Map from Host System Port to Container Port
      ## [ip-address]:[host-system-port]:[container-port]
      - "8080:8191"

