# Docker-compose file 
# for
# NextCloud NAS/file sharing server
# with Networking
version: "3.5"

#volumes:
#   nextcloud:
#   db:

networks:
    # Named, Bridged Networking
    nextcloud_network:

services:
    nextcloud:
        ## NextCloud NAS server
        image: arm32v7/nextcloud:latest
        container_name: nextcloud-app
        networks:
            - nextcloud_network
        restart: unless-stopped
        # depends_on:
            ## Dependencies
            ## - to build these before starting up nextcloud
            ## corresponds with running 'docker run' for all specified services before this
        volumes:
            ## Volumes to mount
            ## Format: [host system volume]:[container volume]:[permissions]
            # WebApp HTML page
            - "${PWD}/nextcloud/app/html:/var/www/html"
            # WebApp Config
            - "${PWD}/nextcloud/app/config:/var/www/html/config"
            # NextCloud Custom Applications
            - "${PWD}/nextcloud/app/custom_apps:/var/www/html/custom_apps"
            # NextCloud Themes
            - "${PWD}/nextcloud/app/themes:/var/www/html/themes"
            # Data folder - to store your NextCloud data
            # - place this volume at whichever location you want to store your data
            # - "${PWD}/nextcloud/app/data:/var/www/html/data"
            - "${PWD}/nextcloud/data:/var/www/html/data"
            - "/etc/localtime:/etc/localtime:ro"
        # ports:
            ## Port Forwarding/Translation 
            ## Format: [host system port]:[container port]
            ## - corresponds with 'docker run -p'
        env_file:
            ## Import environment variables via an environment file
            ## corresponds with running 'docker run -e' multiple times
            ## Contents:
            ##  - VIRTUAL_HOST=nextcloud.[YOUR-DOMAIN] : Your nextcloud domain virtual hostname
            ##  - LETSENCRYPT_HOST=nextcloud.[YOUR-DOMAIN] : Your Let's Encrypt Hostname
            ##  - LETSENCRYPT_EMAIL=[YOUR-EMAIL] : Your Let's Encrypt Email for PKI Authentication
            - "${PWD}/nextcloud/app/.env"
            
