version: "3.7"
services:
  nix:
    image: nixpkgs/nix:latest
    container_name: nix
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      ## Mount volumes from host system into container
      ## [host-system-volume]:[container-volume]:[permissions]
      - ${PWD}/workdir:/workdir


