version: "3.5"

services:
    # Uptime Kuma
    ## System Monitoring utility
    ## For Home Lab Servers
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        restart: always
        ports:
            # [Host system port]:[container port]
            - 3001:3001
        volumes:
            # [host system path]:[container path]:[permissions]
            - "$PWD/uptime-kuma/app/data:/app/data"
