version: "3.7"

services:
    # Pi-hole DNS Server, Resolver, Sinkhole, Firewall, Router
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      restart: always
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "8080:80/tcp"
        - "4443:443/tcp"
      environment:
        ### Timezone and locale
        # TZ: 'Region/City' # This is the timezone
        ### WebUI Environment Variables
        # WEBPASSWORD: "Password-here"
        # WEBPASSWORD_FILE: ./pihole/secrets/WebPasswords # WebUI Password File; Place your WEBPASSWORD secret here; Related to 'WEBPASSWORD'
        ### FTL DNS
        # FTLCONF_LOCAL_IPV4: [your-server-ip] ### Set your server IP here
        # PIHOLE_DNS_: "[your-dns-server-ip]#5335" # DNS Resolver Port 5335
        # ServerIP: [your-host-server-ip]
      volumes:
        - './pihole/etc-pihole/:/etc/pihole/'
        - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      dns:
        - 8.8.8.8
        - 8.8.4.4
      cap_add:
        - NET_ADMIN
      networks:
        dns_net:
          ipv4_address: 172.28.0.2

    unbound:
      image: 'mvance/unbound-rpi:latest'
      container_name: 'unbound'
      ports:
        - "5335:53/tcp"
        - "5335:53/udp"
        # - "5335:5335/tcp" # TCP port number for Unbound DNS resolver; Corresponds to the port number specified in the unbound configuration file
        # - "5335:5335/udp" # UDP port number for Unbound DNS resolver; Corresponds to the port number specified in the unbound configuration file
      environment:
        - TZ=Region/City
      restart: unless-stopped
      volumes:
        - "./unbound.d/etc-unbound/unbound/:/etc/unbound"
      networks:
        dns_net:
          ipv4_address: 172.28.0.3

    wireguard:
      image: linuxserver/wireguard
      container_name: wireguard
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        #- SERVERURL=wireguard.domain.com #optional
        - SERVERPORT=51820 #optional
        - PEERS=1 #optional
        - PEERDNS=auto #optional
        - INTERNAL_SUBNET=192.168.1.0 #optional
        - ALLOWEDIPS=0.0.0.0/0 #optional
        - PERSISTENTKEEPALIVE_PEERS= #optional
        - LOG_CONFS=true #optional
      volumes:
        # - /path/to/appdata/config:/config
        # - "${PWD}/wireguard/config:/config"
        - "./wireguard/config:/config"
        - /lib/modules:/lib/modules #optional
      ports:
        - 51820:51820/udp
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv4.ip_forward=1
        - net.ipv6.conf.all.forwarding=1
      restart: unless-stopped
      networks:
        dns_net:
          ipv4_address: 172.28.0.4

networks:
  ## Specify VLAN group name
  dns_net:
    ## Specify VLAN group properties
    name: dns_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16




