version: "3"

networks:
    default:

volumes:
  # Named mounted volume
  ikev2-vpn-data:

services:
    vpn:
        # Set image
        image: hwdsl2/ipsec-vpn-server
        restart: always
        env_file:
          - ./ipsec-vpn/vpn.env
        ports:
          - "500:500/udp"
          - "4500:4500/udp"
        privileged: true
        hostname: ipsec-vpn-server
        container_name: ipsec-vpn-server
        volumes:
          - ikev2-vpn-data:/etc/ipsec.d/
          - /lib.modules:/lib/modules:ro
